version: '3.9'
services:
  app:
    container_name: usuario_app_container
    build: .
    ports:
      - "7720:7720"
    volumes:
      - usuario-app-data:/app
    networks:
      - entregamaisnetwork
    depends_on:
      - postgres
  

  postgres:
    container_name: usuario_postgres_container
    image: postgres
    environment:
      POSTGRES_USER: ifpb
      POSTGRES_PASSWORD: ifpb
      PGDATA: /data/postgres
    volumes:
      - usuario-postgres-data:/data/postgres
      - usuario-postgres-db-data:/var/lib/postgresql/data
    ports:
      - "7721:5432"
    networks:
      - entregamaisnetwork
    restart: unless-stopped

  # pgadmin:
  #   container_name: pgadmin_container
  #   image: dpage/pgadmin4
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: ifpb@ifpb.edu.br
  #     PGADMIN_DEFAULT_PASSWORD: ifpb
  #     PGADMIN_CONFIG_SERVER_MODE: 'False'
  #   volumes:
  #     - pgadmin-data:/var/lib/pgadmin
  #   ports:
  #     - "7000:80"
  #   networks:
  #     - entregamaisnetwork
  #   depends_on:
  #     - postgres
  #   restart: unless-stopped

networks:
  entregamaisnetwork:
    name: entregamaisnetwork

volumes:
  usuario-app-data:
  usuario-postgres-data:
  usuario-postgres-db-data:
  # usuario-pgadmin-data:
